version: "3.8"
services:
  web:
    # image: nginx:1.18
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    container_name: web

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
    container_name: app

  db:
    # image: mysql:8.0
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d
    command: bash -c 'usermod -o -u $LINUX_MYSQL_UID mysql; groupmod -o -g $LINUX_MYSQL_GID mysql; chown -R mysql:root /var/run/mysqld/ /var/log/mysql/ /var/lib/mysql/; /entrypoint.sh mysqld --user=mysql --console'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTPASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${USERPASS}
      - TZ=${TZ}
    container_name: db