version: "3.8"
services:
  web:
    # AWS ECRリポジトリのdocker imageを利用
    image: 917620984613.dkr.ecr.ap-northeast-1.amazonaws.com/web-makala:latest
    # image: nginx:1.18
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    container_name: web

  app:
    # AWS ECRリポジトリのdocker imageを利用
    image: 917620984613.dkr.ecr.ap-northeast-1.amazonaws.com/app-makala:latest
    # build: ./docker/app
    depends_on:
      - db
    volumes:
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
    container_name: app

  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTPASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${USERPASS}
      - TZ=${TZ}
    container_name: db